// <auto-generated />
using System;
using Akyildiz.Sevkiyat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Akyildiz.Sevkiyat.Infrastructure.Migrations
{
    [DbContext(typeof(SevkiyatDbContext))]
    [Migration("20260117230033_FixStockDecimalPrecision")]
    partial class FixStockDecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Donem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImportStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NetsisOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalepNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalepTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeslimAlacakKisiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeslimAlacakTelefonNumaralari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoneticiMailAdresleri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IssOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryDate = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            ExternalOrderNumber = "SO-1001",
                            ImportStatus = 0,
                            IsActive = true,
                            OrderDate = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            ProjectId = 1,
                            Status = "Imported"
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BirimFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Iskonto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IssOrderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("KDVOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("ListeFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssOrderId");

                    b.ToTable("IssOrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IssOrderId = 1,
                            LineNumber = 1,
                            OrderedQty = 120m,
                            StockCode = "EKMEK-01",
                            StockName = "Somun Ekmek",
                            Unit = "Adet"
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul / Kozyatağı",
                            Code = "PRJ001",
                            IsActive = true,
                            Name = "Kozyatağı Yemekhanesi",
                            Region = "Anadolu-1"
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedDriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedPlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IssOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssOrderId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ShipmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShipmentHistories");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ShipmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DeliveredQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DifferenceReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IssOrderLineId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssOrderLineId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentLines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalStockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalStockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalStockId")
                        .HasColumnType("int");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalStockId");

                    b.ToTable("StockMappings");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StockCode")
                        .IsUnique();

                    b.ToTable("StockMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            StockCode = "EKMEK-01",
                            StockName = "Somun Ekmek"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            StockCode = "SU-05",
                            StockName = "Su 0.5L"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            StockCode = "YOGURT-200",
                            StockName = "Yoğurt 200gr"
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Project", "Project")
                        .WithMany("IssOrders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", "IssOrder")
                        .WithMany("Lines")
                        .HasForeignKey("IssOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssOrder");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Project", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Zone", "Zone")
                        .WithMany("Projects")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", "IssOrder")
                        .WithMany()
                        .HasForeignKey("IssOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Project", "Project")
                        .WithMany("Shipments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssOrder");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ShipmentLine", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", "IssOrderLine")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("IssOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssOrderLine");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockMapping", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", "LocalStock")
                        .WithMany()
                        .HasForeignKey("LocalStockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LocalStock");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", b =>
                {
                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Project", b =>
                {
                    b.Navigation("IssOrders");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Zone", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
