// <auto-generated />
using System;
using Akyildiz.Sevkiyat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Akyildiz.Sevkiyat.Infrastructure.Migrations
{
    [DbContext(typeof(SevkiyatDbContext))]
    [Migration("20260322132701_Faz2_DeliveryPhoto")]
    partial class Faz2_DeliveryPhoto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.FloatingReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("LinkedShipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReturnReason")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StockCodeFree")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StockMasterId")
                        .HasColumnType("int");

                    b.Property<string>("StockNameFree")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LinkedShipmentId");

                    b.HasIndex("StockMasterId");

                    b.ToTable("FloatingReturns");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("WaybillDate")
                        .HasColumnType("date");

                    b.Property<string>("WaybillNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("SupplierId", "WaybillNo", "WaybillDate");

                    b.ToTable("GoodsReceipts");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AcceptedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("PurchaseOrderLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ReceivedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RejectedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockMasterId")
                        .HasColumnType("int");

                    b.Property<string>("StockNameSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitSnapshot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("PurchaseOrderLineId");

                    b.HasIndex("StockMasterId");

                    b.ToTable("GoodsReceiptLines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Donem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImportStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTransferred")
                        .HasColumnType("bit");

                    b.Property<string>("NetsisOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalepNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalepTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeslimAlacakKisiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeslimAlacakTelefonNumaralari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoneticiMailAdresleri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IssOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            ExternalOrderNumber = "SO-1001",
                            ImportStatus = 0,
                            IsActive = true,
                            IsTransferred = false,
                            OrderDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            ProjectId = 1,
                            Status = "Imported"
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BirimFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Iskonto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IssOrderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("KDVOrani")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<decimal?>("ListeFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssOrderId");

                    b.ToTable("IssOrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IssOrderId = 1,
                            LineNumber = 1,
                            OrderedQty = 120m,
                            StockCode = "EKMEK-01",
                            StockName = "Somun Ekmek",
                            Unit = 0
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetsisCariKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul / Kozyatağı",
                            Code = "PRJ001",
                            IsActive = true,
                            Name = "Kozyatağı Yemekhanesi",
                            Region = "Anadolu-1"
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ExpectedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StockMasterId")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("StockMasterId");

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.PurchaseOrderNumberCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LastValue")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PurchaseOrderNumberCounters");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedDriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedPlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryPhotoBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryRecipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("IrsaliyeDate")
                        .HasColumnType("date");

                    b.Property<string>("IrsaliyeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IssOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NetsisTransferredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ReturnNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TalepNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZonePreparationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDate");

                    b.HasIndex("IssOrderId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("ZonePreparationId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ShipmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId", "ChangedAt");

                    b.ToTable("ShipmentHistories");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ShipmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DeliveredQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DifferenceReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IssOrderLineId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReturnReason")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReturnedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StockMasterId")
                        .HasColumnType("int");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssOrderLineId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("StockMasterId");

                    b.ToTable("ShipmentLines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CompletedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CountDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StockCounts");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockCountLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ExpectedQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StockCountId")
                        .HasColumnType("int");

                    b.Property<int>("StockMasterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockCountId");

                    b.HasIndex("StockMasterId");

                    b.ToTable("StockCountLines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalStockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalStockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocalStockId")
                        .HasColumnType("int");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExternalStockCode");

                    b.HasIndex("LocalStockId");

                    b.ToTable("StockMappings");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinStockQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NetsisStockCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OnHandQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<int>("PickingType")
                        .HasColumnType("int");

                    b.Property<decimal>("ReservedQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxRate")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WarehouseLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StockCode")
                        .IsUnique();

                    b.ToTable("StockMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            IsActive = true,
                            OnHandQty = 0m,
                            PickingType = 0,
                            ReservedQty = 0m,
                            StockCode = "EKMEK-01",
                            StockName = "Somun Ekmek",
                            TaxRate = 20,
                            Unit = 0,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            IsActive = true,
                            OnHandQty = 0m,
                            PickingType = 0,
                            ReservedQty = 0m,
                            StockCode = "SU-05",
                            StockName = "Su 0.5L",
                            TaxRate = 20,
                            Unit = 0,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            IsActive = true,
                            OnHandQty = 0m,
                            PickingType = 0,
                            ReservedQty = 0m,
                            StockCode = "YOGURT-200",
                            StockName = "Yoğurt 200gr",
                            TaxRate = 20,
                            Unit = 0,
                            UnitPrice = 0m
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockMasterId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockMasterId", "Date");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Capacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ZonePreparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StartedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ZoneId", "DeliveryDate", "BatchNo")
                        .IsUnique();

                    b.ToTable("ZonePreparations");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ZonePreparationProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAddedLater")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMicroReady")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MicroReadyAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ZonePreparationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ZonePreparationId");

                    b.ToTable("ZonePreparationProjects");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.FloatingReturn", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Shipment", "LinkedShipment")
                        .WithMany()
                        .HasForeignKey("LinkedShipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", "StockMaster")
                        .WithMany()
                        .HasForeignKey("StockMasterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedShipment");

                    b.Navigation("StockMaster");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.GoodsReceipt", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Lines")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", "StockMaster")
                        .WithMany()
                        .HasForeignKey("StockMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");

                    b.Navigation("PurchaseOrderLine");

                    b.Navigation("StockMaster");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Project", "Project")
                        .WithMany("IssOrders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", "IssOrder")
                        .WithMany("Lines")
                        .HasForeignKey("IssOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssOrder");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Project", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Zone", "Zone")
                        .WithMany("Projects")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", "StockMaster")
                        .WithMany()
                        .HasForeignKey("StockMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("StockMaster");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", "IssOrder")
                        .WithMany()
                        .HasForeignKey("IssOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Project", "Project")
                        .WithMany("Shipments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.ZonePreparation", "ZonePreparation")
                        .WithMany()
                        .HasForeignKey("ZonePreparationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IssOrder");

                    b.Navigation("Project");

                    b.Navigation("ZonePreparation");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ShipmentHistory", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Shipment", null)
                        .WithMany("Histories")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ShipmentLine", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", "IssOrderLine")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("IssOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", "StockMaster")
                        .WithMany()
                        .HasForeignKey("StockMasterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IssOrderLine");

                    b.Navigation("Shipment");

                    b.Navigation("StockMaster");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockCountLine", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.StockCount", "StockCount")
                        .WithMany("Lines")
                        .HasForeignKey("StockCountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", "StockMaster")
                        .WithMany()
                        .HasForeignKey("StockMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StockCount");

                    b.Navigation("StockMaster");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockMapping", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", "LocalStock")
                        .WithMany()
                        .HasForeignKey("LocalStockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LocalStock");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockTransaction", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.StockMaster", "StockMaster")
                        .WithMany()
                        .HasForeignKey("StockMasterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StockMaster");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ZonePreparation", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ZonePreparationProject", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.ZonePreparation", "ZonePreparation")
                        .WithMany("Projects")
                        .HasForeignKey("ZonePreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ZonePreparation");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", b =>
                {
                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Project", b =>
                {
                    b.Navigation("IssOrders");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.StockCount", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Zone", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ZonePreparation", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
