// <auto-generated />
using System;
using Akyildiz.Sevkiyat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Akyildiz.Sevkiyat.Infrastructure.Migrations
{
    [DbContext(typeof(SevkiyatDbContext))]
    [Migration("20260114131431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalOrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NetsisOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IssOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            ExternalOrderNumber = "SO-1001",
                            OrderDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ProjectId = 1,
                            Status = "Imported"
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IssOrderId")
                        .HasColumnType("int");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssOrderId");

                    b.ToTable("IssOrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IssOrderId = 1,
                            LineNumber = 1,
                            OrderedQty = 120m,
                            StockCode = "EKMEK-01",
                            StockName = "Somun Ekmek",
                            Unit = "Adet"
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "İstanbul / Kozyatağı",
                            Code = "PRJ001",
                            IsActive = true,
                            Name = "Kozyatağı Yemekhanesi",
                            Region = "Anadolu-1"
                        });
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IssOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssOrderId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ShipmentLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DeliveredQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DifferenceReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IssOrderLineId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<string>("StockCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssOrderLineId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentLines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Project", "Project")
                        .WithMany("IssOrders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", "IssOrder")
                        .WithMany("Lines")
                        .HasForeignKey("IssOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssOrder");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", "IssOrder")
                        .WithMany()
                        .HasForeignKey("IssOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Project", "Project")
                        .WithMany("Shipments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssOrder");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.ShipmentLine", b =>
                {
                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", "IssOrderLine")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("IssOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Akyildiz.Sevkiyat.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IssOrderLine");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.IssOrderLine", b =>
                {
                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Project", b =>
                {
                    b.Navigation("IssOrders");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Akyildiz.Sevkiyat.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
